//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThucTapSinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResults
    {
        public int ID { get; set; }
        public string PersonID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> Answer { get; set; }
    
        public virtual Intern Intern { get; set; }
        public virtual Task Task { get; set; }
    }
}
