//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThucTapSinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string UserName { get; set; }
        public string PersonID { get; set; }
        public string PassWord { get; set; }
        public bool Status { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
